-- Generated by node scripts/build_unis_slice.js. Do not edit by hand.
-- Seeds only the accepted partial unis boundary from data/generated/unis-partial-import.json.
INSERT INTO unis (id, title, address, "desc", lat, long, created_at, updated_at)
VALUES
  (1, 'Atlantic University College', 'Calle Colton #9, GUAYNABO, Puerto Rico', NULL, 18.357558765016, -66.111368701553, TIMESTAMP '2026-06-23 00:00:00', TIMESTAMP '2026-06-23 00:00:00'),
  (2, 'Escuela de Medicina San Juan Bautista', 'Luis A. Ferre Highway Exit #21, Road 172 Caguas to Cidra, Turabo Gardens, Caguas, PR 00725', NULL, 18.207869913262, -66.10592814177, TIMESTAMP '2026-06-23 00:00:00', TIMESTAMP '2026-06-23 00:00:00'),
  (3, 'Trinity College', '#834 Avenida Hostos, PONCE, Puerto Rico', NULL, 17.984663508186, -66.619028663773, TIMESTAMP '2026-06-23 00:00:00', TIMESTAMP '2026-06-23 00:00:00'),
  (4, 'Universidad Politécnica de Puerto Rico', 'Ave. Ponce de León 377, Hato Rey, SAN JUAN, Puerto Rico', 'Academic unit: San Juan', 18.465156173786, -66.097033809568, TIMESTAMP '2026-06-23 00:00:00', TIMESTAMP '2026-06-23 00:00:00');

SELECT setval('unis_id_seq', 4, true);
