FROM node:26-bookworm-slim@sha256:cd565714d4da3e84bfd341e31448f81d47c6362198f152345297c9c1154e6341

WORKDIR /workspace

ENV NODE_ENV=test

COPY .node-version ./
COPY scripts ./scripts/
COPY package.json package-lock.json ./
RUN npm ci
RUN npx playwright install --with-deps
COPY app/package.json app/package-lock.json ./app/
RUN npm --prefix app ci
COPY dtoapi/modern/package.json dtoapi/modern/package-lock.json ./dtoapi/modern/
RUN npm --prefix dtoapi/modern ci

COPY app ./app/
COPY dtoapi ./dtoapi/
COPY data ./data/
COPY test ./test/

CMD ["npm", "run", "test:browser:start-local"]
