FROM node:26-bookworm-slim@sha256:81502e860176e63695d769d3d1a2d3a403abc1c27c6a02169b765f3e43b60ede

WORKDIR /workspace

ENV NODE_ENV=test

COPY .node-version ./
COPY scripts ./scripts/
COPY package.json package-lock.json ./
RUN npm ci
RUN npx playwright install --with-deps
COPY app/package.json app/package-lock.json ./app/
RUN npm --prefix app ci
COPY dtoapi/modern/package.json dtoapi/modern/package-lock.json ./dtoapi/modern/
RUN npm --prefix dtoapi/modern ci

COPY app ./app/
COPY dtoapi ./dtoapi/
COPY data ./data/
COPY test ./test/

CMD ["npm", "run", "test:browser:start-local"]
