FROM postgres:18-alpine

COPY docker/postgres/init.sql /docker-entrypoint-initdb.d/001_contract_data.sql
COPY docker/postgres/002_unis_partial_seed.sql /docker-entrypoint-initdb.d/002_unis_partial_seed.sql
