FROM postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685

COPY docker/postgres/init.sql /docker-entrypoint-initdb.d/001_contract_data.sql
COPY docker/postgres/002_unis_partial_seed.sql /docker-entrypoint-initdb.d/002_unis_partial_seed.sql
